name: Build on Pull Request and Commits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Frontend

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build
